id: I381F9726
ocr_import_info:
  timestamp: '2023-06-28T05:29:24.647742+00:00'
  batch_id: batch-4705
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-28 05:39:05.657605+00:00
last_modified: 2023-06-28 05:39:05.657610+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM1160
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM1160
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐེག་པ་ཆེན་པོ་རྒྱུད་བླ་མའི་བསྟན་བཅོས་རྣམ་པར་བཤད་པ་སོགས།
  languages:
  - bo
  author: སློབ་དཔོན་ཐོགས་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.9500350357411701
  ocr_word_median_confidence_index: 0.99674445
bases:
  I1NLM1160_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM1160_001
      total_pages: 520
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM1160_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.99674445
      ocr_word_mean_confidence_index: 0.9500350357411701
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
